### ISSUE TITLE
ERROR in static/js/vendor.b8806fb0e903c18740bc.js from UglifyJs SyntaxError: Unexpected token: name (warn) [./~/.2.1.0@vue-awesome/util.js:3,0][static/js/vendor.b8806fb0e903c18740bc.js:89356,4]

### ISSUE THREAD

**Issue by hank2718** [Justineo/vue-awesome#27] opened 2017-03-22 09:05 UTC

**Comment by sdeprez** [comment] 2017-03-23 16:47
Duplicate of #18

**Comment by Justineo** [comment] 2017-03-23 17:28
See #18.

**Closed by Justineo** 2017-03-23 17:28 UTC
Labels: duplicate

**Comment by hank2718** [comment] 2017-03-29 04:52
It will still be wrong
  {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/vue-awesome')]
      },

**Comment by hank2718** [comment] 2017-03-29 04:53
for webpack2

**Comment by Justineo** [comment] 2017-03-29 05:39
Are you using Windows? If so, you may try use `resolve('node_modules\\vue-awesome')` instead.

**Comment by hank2718** [comment] 2017-03-29 07:39
using  mac os
