### ISSUE TITLE
[Vue warn]: Unknown custom element: <icon>

### ISSUE THREAD

**Issue by RShadowhand** [Justineo/vue-awesome#28] opened 2017-03-29 15:53 UTC
I'm using a "vue init simple" template (no webpack or anything), and have added
`<script src="lib/js/vue-awesome.js"></script>`  (downloaded and placed at the given path beforehand), however I can't use it. I keep getting the following error:
`[Vue warn]: Unknown custom element: <icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in <Root>)`

I started doubting myself, if I'm doing something wrong, but other packages (namely bootstrap-vue) seems to work without an issue.

**Comment by Justineo** [comment] 2017-03-29 16:53
You should [register the component](https://vuejs.org/v2/guide/components.html#Registration) before you use it.

**Comment by RShadowhand** [comment] 2017-03-29 16:56
I did manage to register it, however it fails to work with 2.2.6. You can close the issue if you'd like.

**Comment by Justineo** [comment] 2017-03-29 18:07
It seems that it's caused by this: https://github.com/vuejs/vue/commit/4b51ad048306367a6fb6fbee7445e086d855f31e.

Try the latest version (`vue-awesome@2.2.2`) and it should work correctly with `vue@2.2.6`.

**Comment by RShadowhand** [comment] 2017-03-29 18:13
Now I'm getting this:
`ReferenceError: exports is not defined vue-awesome.js:1:8268`

**Comment by Justineo** [comment] 2017-03-29 18:25
Oops. The quick fix seem to introduce another problem. I'll dig into this ASAP.

**Comment by Justineo** [comment] 2017-03-29 19:00
Fixed in `vue-awesome@2.2.3`.

**Closed by Justineo** 2017-03-29 19:00 UTC

**Comment by EmptyBox-Design** [comment] 2018-12-21 20:42
I am on 
vue:  `2.5.21`
vue-awesome: `3.2.0`

Receiving this error `Unknown custom element: <icon>`
