### ISSUE TITLE
Icon disappears when a put in a link which is not a direct parent to the component

### ISSUE THREAD

**Issue by lucvandewall** [Justineo/vue-awesome#100] opened 2018-04-20 06:17 UTC
When creating a link (in this case with vue-bootstrap) as a direct parent of the component the icon works as expected:
`<b-col cols="12" md="2"><b-link v-b-modal.myRatingModal><icon name="star" scale="3"></icon></b-link></b-col>`

When it is however not a direct parent the icon disappears:
`<b-link v-b-modal.myRatingModal><b-col cols="12" md="2"><icon name="star" scale="3"></icon></b-col></b-link>`

I fixed it by giving the .fa-icon class a min-width

**Comment by Justineo** [comment] 2018-04-20 06:42
https://codesandbox.io/s/m3l8301rvy

I don't think it's caused by Vue-Awesome.

**Comment by lucvandewall** [comment] 2018-04-20 06:44
Yes, I went back to my code and put 

`display: inline-block` on the b-col 

Sorry for the inconvenience

**Comment by Justineo** [comment] 2018-04-20 06:46
Never mind. So I'm closing this.

**Closed by Justineo** 2018-04-20 06:46 UTC
