### ISSUE TITLE
Clarification on correct import for loading individual icons?

### ISSUE THREAD

**Issue by paultopia** [Justineo/vue-awesome#44] opened 2017-06-15 00:57 UTC
Hi there, 

The readme doesn't seem to be quite correct on the right way to load individual icons.  

First of all, 

According to the readme as it stands right now, the correct import statement to register the component is: `import Icon from 'vue-awesome/components/Icon'`.  But even with vue-loader, that doesn't work at all.  Instead, it seems to insist on being passed the .vue extension, or node can't find the component at all. `import Icon from 'vue-awesome/components/Icon.vue'` works fine.

Second, it doesn't seem to actually be importing single icons.  I'm only importing 11 icons, and webpack-bundle-size-analyzer reports that vue-awesome is using a gigantic 477.76 KB---which has gotta be the entire thing. 

Maybe I'm doing something wrong?  I don't think so, but just in case, below is the relevant code I have...

```
import Icon from 'vue-awesome/components/Icon.vue';
Vue.component('icon', Icon);
import 'vue-awesome/icons/phone';
import 'vue-awesome/icons/certificate';
import 'vue-awesome/icons/cogs';
import 'vue-awesome/icons/file-text';
import 'vue-awesome/icons/external-link-square';
import 'vue-awesome/icons/download';
import 'vue-awesome/icons/times';
import 'vue-awesome/icons/file-pdf-o';
import 'vue-awesome/icons/envelope-o';
import 'vue-awesome/icons/list-ul';
import 'vue-awesome/icons/pencil';
```

**Comment by depfryer** [comment] 2017-06-15 03:49
import {phone, certificate,....}from 'vue-awesone/icons'
dosn't work ?

**Comment by paultopia** [comment] 2017-06-15 04:50
That made the bundle size even bigger (!!) now we're up to 984.81 KB for vue-awesome via `webpack --json | webpack-bundle-size-analyzer`.

**Comment by Justineo** [comment] 2017-06-15 08:19
Are you using vue-cli to scaffold your project? With vue-cli's built-in configs, I cannot reproduce your problem.

After `vue init webpack project` and added a flag icon to the demo, I got this:

![image](https://user-images.githubusercontent.com/1726061/27172020-4c8d80de-51e6-11e7-87ee-c4ec4dd7cb41.png)

And I import icons like this:

```js
import Icon from 'vue-awesome/components/Icon'
import 'vue-awesome/icons/flag'
```

**Comment by paultopia** [comment] 2017-06-15 13:02
Hmm.  Odd, I was using vie-cli, but I've tweaked a bunch of things.  Maybe I broke something---will reconfigure and see if that fixes...

---
Paul Gowder 
http://paul-gowder.com

My book: The Rule of Law in the Real World
http://rulelaw.net

**Comment by Justineo** [comment] 2017-07-20 06:03
Closing this for now. Feel free to reopen if you still cannot make it work.

**Closed by Justineo** 2017-07-20 06:03 UTC
