### ISSUE TITLE
Uglify.js chokes on Icon.vue [v2.3.1]

### ISSUE THREAD

**Issue by dschreij** [Justineo/vue-awesome#46] opened 2017-06-30 21:12 UTC
When bundling the assets of my project for production, Uglify seems to trip over something in Icon.vue:

~~~
error

/js/app.js from UglifyJs
Unexpected token: name (icons) [Icon.vue?8a3472bc:50,0][/js/app.js:11686,4]
~~~

Do you have any idea what this could be? Thanks!

**Comment by Justineo** [comment] 2017-07-02 04:46
Are you using vue-loader and babel? It looks like the Vue component is not properly transpiled before Uglify.js handles it.

**Comment by dschreij** [comment] 2017-07-02 17:08
Yes, I am using vue-loader and Babel. I use many vue components and modules and they compile just fine, so I don't know why this happens here.

**Comment by Justineo** [comment] 2017-07-03 02:28
Could you pls provide more detailed steps to reproduce the problem?

**Comment by dschreij** [comment] 2017-07-03 12:47
Hmm that is more difficult:

I am using vue2 (and vue-awesome) together with [Laravel 5.4](http://laravel.com/), which uses [laravel-mix](https://github.com/JeffreyWay/laravel-mix) to do the bulk of the webpack configuration. 
I don't have the problem when creating a developer build with `npm run dev`, but it does occur when doing a production build with `npm run prod`. The main difference here is that the script is minified and uglified, and I think the problem occurs with the uglification process. 

Don't worry about this problem if I'm the only one experiencing it; I just wanted to bring it up your radar so you know there might be something going on with vue-awesome and Uglify. 
I did some further research and I found that this might be an uglify problem: https://github.com/webpack/webpack/issues/2972, so let's await if it gets fixed over there first.

**Comment by depfryer** [comment] 2017-07-10 12:39
i am the problem ^^
and in dev mode (into IE)
and compil into console
```log
ERROR in static/js/app.b7c4c038f02e17c46809.js from UglifyJs
Unexpected token: name (icons) [Icon.vue?8a3472bc:50,0][static/js/app.b7c4c038f02e17c46809.js:2652,4]
```
i'm in a JS app only

and in my main i have 
````
import 'vue-awesome/icons'
import Icon from 'vue-awesome/components/Icon'
....
Vue.component('icon', Icon)
```

**Comment by depfryer** [comment] 2017-07-10 13:35
i thinks i found a way
i create a .babel
with 
```
{
  "presets": [
    [
      "env" ,
      {
        "modules": false
      }
    ]
  ]
}
```

**Comment by Justineo** [comment] 2017-07-23 10:11
@dschreij

Actually the precompiled version of Vue-Awesome is uglified and it went well. I think your problem is that Babel might not be working properly while UglifyJS only handles ES5 code.

I'll close this issue for now because I cannot reproduce the problem when ES next code is properly transpiled before UglifyJS start to work.

**Closed by Justineo** 2017-07-23 10:11 UTC

**Comment by villlem** [comment] 2018-03-01 12:44
We bump into simillar issue ourselves. On developers machines build works but it fails during automatic build for deployment. Turns out that on our build machine `node_modules` was symlink to other location. If we replace it with direct copy everything works. Maybe now you can investigate further.

**Comment by dsbert** [comment] 2018-03-07 15:52
I ran into this problem as soon as I switched to using yarn workspaces, which symlinks the packages, so @villlem might be on to something.
